title: UHS MRI Physics Team Journal Lounge
description: Collect journal contents for the MRI Physics Team at University Hospial Southampton NHS Foundation Trust
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
        - jekyll-remote-theme # add this line to the plugins list if you already have one
